<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\api\v1\models\base;

use Yii;

/**
 * This is the base-model class for table "alumno".
 *
 * @property integer $id
 * @property integer $id_persona
 * @property integer $id_grupofamiliar
 * @property integer $id_divisionescolar
 * @property string $fecha_ingreso
 * @property string $fecha_egreso
 * @property string $nro_legajo
 * @property boolean $activo
 * @property boolean $hijo_profesor
 * @property boolean $egresado
 *
 * @property \app\modules\api\v1\models\BonificacionAlumno[] $bonificacionAlumnos
 * @property \app\modules\api\v1\models\DivisionEscolar $divisionescolar
 * @property \app\modules\api\v1\models\GrupoFamiliar $grupofamiliar
 * @property \app\modules\api\v1\models\Persona $persona
 * @property \app\modules\api\v1\models\ServicioAlumno[] $servicioAlumnos
 * @property string $aliasModel
 */
abstract class Alumno extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'alumno';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_persona', 'id_grupofamiliar', 'id_divisionescolar', 'nro_legajo', 'activo'], 'required'],
            [['id_persona', 'id_grupofamiliar', 'id_divisionescolar'], 'default', 'value' => null],
            [['id_persona', 'id_grupofamiliar', 'id_divisionescolar'], 'integer'],
            [['fecha_ingreso', 'fecha_egreso'], 'safe'],
            [['activo', 'hijo_profesor', 'egresado'], 'boolean'],
            [['nro_legajo'], 'string', 'max' => 25],
            [['id_divisionescolar'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\api\v1\models\DivisionEscolar::className(), 'targetAttribute' => ['id_divisionescolar' => 'id']],
            [['id_grupofamiliar'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\api\v1\models\GrupoFamiliar::className(), 'targetAttribute' => ['id_grupofamiliar' => 'id']],
            [['id_persona'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\api\v1\models\Persona::className(), 'targetAttribute' => ['id_persona' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_persona' => 'Id Persona',
            'id_grupofamiliar' => 'Id Grupofamiliar',
            'id_divisionescolar' => 'Id Divisionescolar',
            'fecha_ingreso' => 'Fecha Ingreso',
            'fecha_egreso' => 'Fecha Egreso',
            'nro_legajo' => 'Nro Legajo',
            'activo' => 'Activo',
            'hijo_profesor' => 'Hijo Profesor',
            'egresado' => 'Egresado',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBonificacionAlumnos()
    {
        return $this->hasMany(\app\modules\api\v1\models\BonificacionAlumno::className(), ['id_alumno' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDivisionescolar()
    {
        return $this->hasOne(\app\modules\api\v1\models\DivisionEscolar::className(), ['id' => 'id_divisionescolar']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGrupofamiliar()
    {
        return $this->hasOne(\app\modules\api\v1\models\GrupoFamiliar::className(), ['id' => 'id_grupofamiliar']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPersona()
    {
        return $this->hasOne(\app\modules\api\v1\models\Persona::className(), ['id' => 'id_persona']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServicioAlumnos()
    {
        return $this->hasMany(\app\modules\api\v1\models\ServicioAlumno::className(), ['id_alumno' => 'id']);
    }




}
